require_relative 'variable.rb'
require_relative 'add.rb'
require_relative 'multiply.rb'
require_relative 'number.rb'
require_relative 'boolean.rb'
require_relative 'more_than.rb'
require_relative 'less_than.rb'
